content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    filename: "{fields.title|slugify}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Content
        type: rich-text

media:
  input: static/images
  output: /images
