baseURL = "https://lorenzogirardi.github.io/website"
locale = "en-us"
title = "Lorenzo's Blog"
theme = "PaperMod"
paginate = 10

[params]
  author = "Lorenzo"
  description = "Personal blog"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Hi there"
  Content = "Any sufficiently advanced technology is indistinguishable from magic."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lorenzogirardi"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Whoami"
    url = "/whoami/"
    weight = 3
